# Data Analysis

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,confusion_matrix,classification_report

In [2]:
data=pd.read_csv("C:/Users/Shafiq/Desktop/arsh LU/adult income/adult_cleanedenc.csv")

data

age  workclass  fnlwgt  education  education.num  marital.status  \
0       38          5  164526         14             15               4   
1       52          3  129177          9             13               6   
2       32          3  136204         12             14               5   
3       51          3  172175         10             16               4   
4       46          3   45363         14             15               0   
...    ...        ...     ...        ...            ...             ...   
31809   22          3  310152         15             10               4   
31810   27          3  257302          7             12               2   
31811   40          3  154374         11              9               2   
31812   58          3  151910         11              9               6   
31813   22          3  201490         11              9               4   

       occupation  relationship  race  sex  capital.gain  capital.loss  \
0               9             1     4    1             0          2824   
1               7             1     4    0             0          2824   
2               3             1     4    1             0          2824   
3               2             1     4    1             0          2824   
4               9             1     4    1             0          2824   
...           ...           ...   ...  ...           ...           ...   
31809          10             1     4    1             0             0   
31810          12             5     4    0             0             0   
31811           6             0     4    1             0             0   
31812           0             4     4    0             0             0   
31813           0             3     4    1             0             0   

       hours.per.week  native.country  income  
0                  45              38       1  
1                  20              38       1  
2                  55              38       1  
3                  40              38       1  
4                  40              38       1  
...               ...             ...     ...  
31809              40              38       0  
31810              38              38       0  
31811              40              38       1  
31812              40              38       0  
31813              20              38       0  

[31814 rows x 15 columns]

In [3]:
data.dtypes

age               int64
workclass         int64
fnlwgt            int64
education         int64
education.num     int64
marital.status    int64
occupation        int64
relationship      int64
race              int64
sex               int64
capital.gain      int64
capital.loss      int64
hours.per.week    int64
native.country    int64
income            int64
dtype: object

In [4]:
data.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [5]:
data.describe().T

count           mean            std      min       25%  \
age             31814.0      38.398975      13.623158     17.0      27.0   
workclass       31814.0       3.089143       1.106858      0.0       3.0   
fnlwgt          31814.0  189023.505909  102436.080115  12285.0  117779.0   
education       31814.0      10.280694       3.890929      0.0       9.0   
education.num   31814.0      10.024046       2.549523      1.0       9.0   
marital.status  31814.0       2.621173       1.511244      0.0       2.0   
occupation      31814.0       5.727101       4.021454      0.0       2.0   
relationship    31814.0       1.459043       1.605402      0.0       0.0   
race            31814.0       3.664802       0.849455      0.0       4.0   
sex             31814.0       0.666090       0.471615      0.0       0.0   
capital.gain    31814.0     317.261426    1372.139899      0.0       0.0   
capital.loss    31814.0      87.975954     401.322159      0.0       0.0   
hours.per.week  31814.0      40.281857      12.305898      1.0      40.0   
native.country  31814.0      36.410417       6.063936      0.0      38.0   
income          31814.0       0.224209       0.417067      0.0       0.0   

                     50%        75%       max  
age                 37.0      47.00      90.0  
workclass            3.0       3.00       7.0  
fnlwgt          178419.0  236909.25  799281.0  
education           11.0      12.00      15.0  
education.num       10.0      12.00      16.0  
marital.status       2.0       4.00       6.0  
occupation           6.0       9.00      13.0  
relationship         1.0       3.00       5.0  
race                 4.0       4.00       4.0  
sex                  1.0       1.00       1.0  
capital.gain         0.0       0.00   11678.0  
capital.loss         0.0       0.00    2824.0  
hours.per.week      40.0      45.00      99.0  
native.country      38.0      38.00      40.0  
income               0.0       0.00       1.0

In [6]:
data["income"].value_counts()

0    24681
1     7133
Name: income, dtype: int64

# Treating imbalance

In [7]:
x=data.drop("income",axis=1)
y=data["income"]

In [8]:
from imblearn.over_sampling import SMOTE
sm=SMOTE(sampling_strategy="minority",random_state=0)

In [9]:
x_sm,y_sm=sm.fit_resample(x,y)

In [10]:
y_sm.value_counts()

1    24681
0    24681
Name: income, dtype: int64

In [11]:
x_sm

age  workclass  fnlwgt  education  education.num  marital.status  \
0       38          5  164526         14             15               4   
1       52          3  129177          9             13               6   
2       32          3  136204         12             14               5   
3       51          3  172175         10             16               4   
4       46          3   45363         14             15               0   
...    ...        ...     ...        ...            ...             ...   
49357   40          3  169409         11              9               2   
49358   29          3  353800         15             10               1   
49359   48          3  257324         15             10               2   
49360   46          3  288504         13              9               2   
49361   53          3   99696         14             10               2   

       occupation  relationship  race  sex  capital.gain  capital.loss  \
0               9             1     4    1             0          2824   
1               7             1     4    0             0          2824   
2               3             1     4    1             0          2824   
3               2             1     4    1             0          2824   
4               9             1     4    1             0          2824   
...           ...           ...   ...  ...           ...           ...   
49357           2             0     4    1             0             0   
49358           1             4     2    0          2518             0   
49359           2             0     3    1             0             0   
49360           4             0     2    1             0             0   
49361          10             4     4    0             0             0   

       hours.per.week  native.country  
0                  45              38  
1                  20              38  
2                  55              38  
3                  40              38  
4                  40              38  
...               ...             ...  
49357              48              38  
49358              40              38  
49359              50              37  
49360              48              28  
49361              50               6  

[49362 rows x 14 columns]

In [12]:
data_balance=x_sm.copy()
data_balance["income"]=y_sm
data_balance

age  workclass  fnlwgt  education  education.num  marital.status  \
0       38          5  164526         14             15               4   
1       52          3  129177          9             13               6   
2       32          3  136204         12             14               5   
3       51          3  172175         10             16               4   
4       46          3   45363         14             15               0   
...    ...        ...     ...        ...            ...             ...   
49357   40          3  169409         11              9               2   
49358   29          3  353800         15             10               1   
49359   48          3  257324         15             10               2   
49360   46          3  288504         13              9               2   
49361   53          3   99696         14             10               2   

       occupation  relationship  race  sex  capital.gain  capital.loss  \
0               9             1     4    1             0          2824   
1               7             1     4    0             0          2824   
2               3             1     4    1             0          2824   
3               2             1     4    1             0          2824   
4               9             1     4    1             0          2824   
...           ...           ...   ...  ...           ...           ...   
49357           2             0     4    1             0             0   
49358           1             4     2    0          2518             0   
49359           2             0     3    1             0             0   
49360           4             0     2    1             0             0   
49361          10             4     4    0             0             0   

       hours.per.week  native.country  income  
0                  45              38       1  
1                  20              38       1  
2                  55              38       1  
3                  40              38       1  
4                  40              38       1  
...               ...             ...     ...  
49357              48              38       1  
49358              40              38       1  
49359              50              37       1  
49360              48              28       1  
49361              50               6       1  

[49362 rows x 15 columns]

# Feature Selection on basis of data analysis

In [13]:
data_balance.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [14]:
x=data_balance.drop(["income","workclass","fnlwgt","native.country"],axis=1)
y=data_balance["income"]

In [15]:
x

age  education  education.num  marital.status  occupation  \
0       38         14             15               4           9   
1       52          9             13               6           7   
2       32         12             14               5           3   
3       51         10             16               4           2   
4       46         14             15               0           9   
...    ...        ...            ...             ...         ...   
49357   40         11              9               2           2   
49358   29         15             10               1           1   
49359   48         15             10               2           2   
49360   46         13              9               2           4   
49361   53         14             10               2          10   

       relationship  race  sex  capital.gain  capital.loss  hours.per.week  
0                 1     4    1             0          2824              45  
1                 1     4    0             0          2824              20  
2                 1     4    1             0          2824              55  
3                 1     4    1             0          2824              40  
4                 1     4    1             0          2824              40  
...             ...   ...  ...           ...           ...             ...  
49357             0     4    1             0             0              48  
49358             4     2    0          2518             0              40  
49359             0     3    1             0             0              50  
49360             0     2    1             0             0              48  
49361             4     4    0             0             0              50  

[49362 rows x 11 columns]

In [16]:
y

0        1
1        1
2        1
3        1
4        1
        ..
49357    1
49358    1
49359    1
49360    1
49361    1
Name: income, Length: 49362, dtype: int64

In [17]:
y.value_counts()

1    24681
0    24681
Name: income, dtype: int64

# Preparing and Scaling train and test dataset

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [19]:
print("x_train shape: ",x_train.shape)
print("y_train shape: ",y_train.shape)
print("x_test shape: ",x_test.shape)
print("y_test shape: ",y_test.shape)

x_train shape:  (39489, 11)
y_train shape:  (39489,)
x_test shape:  (9873, 11)
y_test shape:  (9873,)


In [20]:
y_train.value_counts()

1    19745
0    19744
Name: income, dtype: int64

In [21]:
y_test.value_counts()

0    4937
1    4936
Name: income, dtype: int64

# Scaling x_train and x_test

In [22]:
from sklearn.preprocessing import StandardScaler
sc1=StandardScaler()
sc2=StandardScaler()

In [23]:
x_test=sc1.fit_transform(x_test)
x_train=sc2.fit_transform(x_train)

In [24]:
x_train

array([[-0.83293788,  1.37437958, -0.17023658, ..., -0.29062719,
        -0.26723629,  0.17639359],
       [ 1.04322358,  0.49230018,  0.24424473, ..., -0.29062719,
        -0.26723629,  1.40910405],
       [-0.99608235, -0.38977922,  1.07320734, ..., -0.29062719,
        -0.26723629,  0.52859658],
       ...,
       [ 0.79850687,  0.19827372,  0.65872603, ..., -0.29062719,
        -0.26723629, -0.08775865],
       [ 0.79850687,  1.37437958, -0.17023658, ..., -0.29062719,
        -0.26723629, -0.1758094 ],
       [-1.3223713 ,  0.19827372, -0.58471789, ..., -0.29062719,
        -0.26723629, -0.43996164]])

In [25]:
x_test

array([[ 0.22954812, -0.39331971, -0.18107063, ..., -0.27943192,
        -0.27185931, -0.23806865],
       [ 2.00794835,  0.18852708, -0.59623791, ..., -0.27943192,
        -0.27185931, -0.15046656],
       [-0.49797925,  0.18852708, -0.59623791, ..., -0.27943192,
        -0.27185931, -0.15046656],
       ...,
       [-1.22550661, -3.0116303 , -1.84173975, ..., -0.27943192,
        -0.27185931, -1.46449798],
       [-0.3363065 ,  0.18852708, -0.59623791, ..., -0.27943192,
         3.73810698, -0.15046656],
       [-0.25547012, -0.39331971,  1.47959849, ..., -0.27943192,
        -0.27185931, -0.23806865]])

# ML Modelling

# Logistic Regression

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
logreg=LogisticRegression()

In [28]:
logreg.fit(x_train,y_train)
y_train_pred=logreg.predict(x_train)
y_test_pred=logreg.predict(x_test)

print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
print("confusion_matrix train:\n",confusion_matrix(y_train,y_train_pred))
print("classification_report train:\n",classification_report(y_train,y_train_pred))
print("Precision train: ",precision_score(y_train,y_train_pred),"\n")

print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
print("confusion_matrix test:\n",confusion_matrix(y_test,y_test_pred))
print("classification_report test:\n",classification_report(y_test,y_test_pred))
print("Precision test: ",precision_score(y_test,y_test_pred))

Accuracy train:  0.7592494112284434
confusion_matrix train:
 [[14523  5221]
 [ 4286 15459]]
classification_report train:
               precision    recall  f1-score   support

           0       0.77      0.74      0.75     19744
           1       0.75      0.78      0.76     19745

    accuracy                           0.76     39489
   macro avg       0.76      0.76      0.76     39489
weighted avg       0.76      0.76      0.76     39489

Precision train:  0.7475338491295939 

Accuracy test:  0.7631925453256355
confusion_matrix test:
 [[3624 1313]
 [1025 3911]]
classification_report test:
               precision    recall  f1-score   support

           0       0.78      0.73      0.76      4937
           1       0.75      0.79      0.77      4936

    accuracy                           0.76      9873
   macro avg       0.76      0.76      0.76      9873
weighted avg       0.76      0.76      0.76      9873

Precision test:  0.7486600306278713


# Logreg not working very vell trying Hyperparamater Tuning

# Hyperparamater Tuning

In [29]:
for c in np.logspace(-5,8,15):
    
    print("at C: ",c,"\n")
    logreg=LogisticRegression(C=c)
    logreg.fit(x_train,y_train)
    y_train_pred=logreg.predict(x_train)
    y_test_pred=logreg.predict(x_test)
    
    print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
    print("Precision train: ",precision_score(y_train,y_train_pred),"\n")
    print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
    print("Precision test: ",precision_score(y_test,y_test_pred),"\n")   
    

at C:  1e-05 

Accuracy train:  0.7543619742206691
Precision train:  0.7221460480339688 

Accuracy test:  0.7583308011749215
Precision test:  0.7236057523675903 

at C:  8.483428982440725e-05 

Accuracy train:  0.759806528400314
Precision train:  0.7339474644290405 

Accuracy test:  0.7618758229514838
Precision test:  0.7321717262439374 

at C:  0.0007196856730011522 

Accuracy train:  0.7612246448378029
Precision train:  0.7449192782526116 

Accuracy test:  0.7657247037374658
Precision test:  0.7453695042095416 

at C:  0.006105402296585327 

Accuracy train:  0.7594266757831295
Precision train:  0.7468079980727536 

Accuracy test:  0.7641041223538945
Precision test:  0.7489020431544777 

at C:  0.05179474679231213 

Accuracy train:  0.7593760287675049
Precision train:  0.7475470056551791 

Accuracy test:  0.7629899726526892
Precision test:  0.748468606431853 

at C:  0.4393970560760795 

Accuracy train:  0.7592747347362556
Precision train:  0.7475699985492529 

Accuracy test:  0.76319

In [30]:
logreg.fit(x_train,y_train)
y_train_pred=logreg.predict(x_train)
y_test_pred=logreg.predict(x_test)

print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
print("confusion_matrix train:\n",confusion_matrix(y_train,y_train_pred))
print("classification_report train:\n",classification_report(y_train,y_train_pred))
print("Precision train: ",precision_score(y_train,y_train_pred),"\n")

print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
print("confusion_matrix test:\n",confusion_matrix(y_test,y_test_pred))
print("classification_report test:\n",classification_report(y_test,y_test_pred))
print("Precision test: ",precision_score(y_test,y_test_pred))

Accuracy train:  0.7592494112284434
confusion_matrix train:
 [[14523  5221]
 [ 4286 15459]]
classification_report train:
               precision    recall  f1-score   support

           0       0.77      0.74      0.75     19744
           1       0.75      0.78      0.76     19745

    accuracy                           0.76     39489
   macro avg       0.76      0.76      0.76     39489
weighted avg       0.76      0.76      0.76     39489

Precision train:  0.7475338491295939 

Accuracy test:  0.7631925453256355
confusion_matrix test:
 [[3624 1313]
 [1025 3911]]
classification_report test:
               precision    recall  f1-score   support

           0       0.78      0.73      0.76      4937
           1       0.75      0.79      0.77      4936

    accuracy                           0.76      9873
   macro avg       0.76      0.76      0.76      9873
weighted avg       0.76      0.76      0.76      9873

Precision test:  0.7486600306278713


# Not much difference in performance of logreg

# SVC

In [38]:
from sklearn.svm import SVC
svc=SVC()

In [39]:
svc.fit(x_train,y_train)
y_train_pred=svc.predict(x_train)
y_test_pred=svc.predict(x_test)

print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
print("confusion_matrix train:\n",confusion_matrix(y_train,y_train_pred))
print("classification_report train:\n",classification_report(y_train,y_train_pred))
print("Precision train: ",precision_score(y_train,y_train_pred),"\n")

print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
print("confusion_matrix test:\n",confusion_matrix(y_test,y_test_pred))
print("classification_report test:\n",classification_report(y_test,y_test_pred))
print("Precision test: ",precision_score(y_test,y_test_pred))

Accuracy train:  0.8543138595558257
confusion_matrix train:
 [[16014  3730]
 [ 2023 17722]]
classification_report train:
               precision    recall  f1-score   support

           0       0.89      0.81      0.85     19744
           1       0.83      0.90      0.86     19745

    accuracy                           0.85     39489
   macro avg       0.86      0.85      0.85     39489
weighted avg       0.86      0.85      0.85     39489

Precision train:  0.8261234383740443 

Accuracy test:  0.8494885040008103
confusion_matrix test:
 [[3943  994]
 [ 492 4444]]
classification_report test:
               precision    recall  f1-score   support

           0       0.89      0.80      0.84      4937
           1       0.82      0.90      0.86      4936

    accuracy                           0.85      9873
   macro avg       0.85      0.85      0.85      9873
weighted avg       0.85      0.85      0.85      9873

Precision test:  0.8172122103714601


#  HyperParameter Tuning

In [76]:
c_val=[10,100,1000]
for c in c_val:
    
    print("at C: ",c,"\n")
    svc=SVC(C=c)
    svc.fit(x_train,y_train)
    y_train_pred=svc.predict(x_train)
    y_test_pred=svc.predict(x_test)
    
    print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
    print("Precision train: ",precision_score(y_train,y_train_pred),"\n")
    print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
    print("Precision test: ",precision_score(y_test,y_test_pred),"\n")
    

at C:  10 

Accuracy train:  0.8688748765478994
Precision train:  0.8401120709782862 

Accuracy test:  0.8565785475539349
Precision test:  0.8230543318649045 

at C:  100 

Accuracy train:  0.885765656258705
Precision train:  0.861440637752681 

Accuracy test:  0.8605287146763901
Precision test:  0.8313163284304599 

at C:  1000 

Accuracy train:  0.9008584669148371
Precision train:  0.8830703707288743 

Accuracy test:  0.8604274283399169
Precision test:  0.837059492231906 



# SVC has better accuracy than Logistic Regression 

# KNN

In [32]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)

In [33]:
knn.fit(x_train,y_train)
y_train_pred=knn.predict(x_train)
y_test_pred=knn.predict(x_test)

print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
print("confusion_matrix train:\n",confusion_matrix(y_train,y_train_pred))
print("classification_report train:\n",classification_report(y_train,y_train_pred))
print("Precision train: ",precision_score(y_train,y_train_pred),"\n")

print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
print("confusion_matrix test:\n",confusion_matrix(y_test,y_test_pred))
print("classification_report test:\n",classification_report(y_test,y_test_pred))
print("Precision test: ",precision_score(y_test,y_test_pred))

Accuracy train:  0.8980222340398591
confusion_matrix train:
 [[17712  2032]
 [ 1995 17750]]
classification_report train:
               precision    recall  f1-score   support

           0       0.90      0.90      0.90     19744
           1       0.90      0.90      0.90     19745

    accuracy                           0.90     39489
   macro avg       0.90      0.90      0.90     39489
weighted avg       0.90      0.90      0.90     39489

Precision train:  0.897280355879082 

Accuracy test:  0.8565785475539349
confusion_matrix test:
 [[4193  744]
 [ 672 4264]]
classification_report test:
               precision    recall  f1-score   support

           0       0.86      0.85      0.86      4937
           1       0.85      0.86      0.86      4936

    accuracy                           0.86      9873
   macro avg       0.86      0.86      0.86      9873
weighted avg       0.86      0.86      0.86      9873

Precision test:  0.8514376996805112


# Hyperparamater Tuning

In [34]:
k_val=[1,2,3,4]
for k in k_val:
    
    print("at K: ",k,"\n")
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(x_train,y_train)
    y_train_pred=knn.predict(x_train)
    y_test_pred=knn.predict(x_test)
    
    print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
    print("Precision train: ",precision_score(y_train,y_train_pred),"\n")
    print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
    print("Precision test: ",precision_score(y_test,y_test_pred),"\n")

at K:  1 

Accuracy train:  0.9673326749221303
Precision train:  0.9678547888252295 

Accuracy test:  0.8422971741112124
Precision test:  0.8358179288411847 

at K:  2 

Accuracy train:  0.9143052495631695
Precision train:  0.9913508318817947 

Accuracy test:  0.8314595361085789
Precision test:  0.8982473222979552 

at K:  3 

Accuracy train:  0.9148117197194156
Precision train:  0.9150661328738661 

Accuracy test:  0.8538438164691583
Precision test:  0.8516206965975438 

at K:  4 

Accuracy train:  0.896325559016435
Precision train:  0.9390182328190744 

Accuracy test:  0.8460447685607212
Precision test:  0.8822739480752014 



In [36]:
k_val=[8,9,10,11]
for k in k_val:
    
    print("at K: ",k,"\n")
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(x_train,y_train)
    y_train_pred=knn.predict(x_train)
    y_test_pred=knn.predict(x_test)
    
    print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
    print("Precision train: ",precision_score(y_train,y_train_pred),"\n")
    print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
    print("Precision test: ",precision_score(y_test,y_test_pred),"\n")

at K:  8 

Accuracy train:  0.8815113069462381
Precision train:  0.900990099009901 

Accuracy test:  0.8548566798338904
Precision test:  0.8700612719205578 

at K:  9 

Accuracy train:  0.8806503076806199
Precision train:  0.8773850170717011 

Accuracy test:  0.8593132786387117
Precision test:  0.8525144106539455 

at K:  10 

Accuracy train:  0.8772569576337714
Precision train:  0.890286073561773 

Accuracy test:  0.8556669705256761
Precision test:  0.8650447078394676 

at K:  11 

Accuracy train:  0.8758894882119072
Precision train:  0.8711 

Accuracy test:  0.8583004152739795
Precision test:  0.8499901048881853 



In [37]:
knn=KNeighborsClassifier(n_neighbors=10)
knn.fit(x_train,y_train)
y_train_pred=knn.predict(x_train)
y_test_pred=knn.predict(x_test)

print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
print("confusion_matrix train:\n",confusion_matrix(y_train,y_train_pred))
print("classification_report train:\n",classification_report(y_train,y_train_pred))
print("Precision train: ",precision_score(y_train,y_train_pred),"\n")

print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
print("confusion_matrix test:\n",confusion_matrix(y_test,y_test_pred))
print("classification_report test:\n",classification_report(y_test,y_test_pred))
print("Precision test: ",precision_score(y_test,y_test_pred))

Accuracy train:  0.8772569576337714
confusion_matrix train:
 [[17650  2094]
 [ 2753 16992]]
classification_report train:
               precision    recall  f1-score   support

           0       0.87      0.89      0.88     19744
           1       0.89      0.86      0.88     19745

    accuracy                           0.88     39489
   macro avg       0.88      0.88      0.88     39489
weighted avg       0.88      0.88      0.88     39489

Precision train:  0.890286073561773 

Accuracy test:  0.8556669705256761
confusion_matrix test:
 [[4288  649]
 [ 776 4160]]
classification_report test:
               precision    recall  f1-score   support

           0       0.85      0.87      0.86      4937
           1       0.87      0.84      0.85      4936

    accuracy                           0.86      9873
   macro avg       0.86      0.86      0.86      9873
weighted avg       0.86      0.86      0.86      9873

Precision test:  0.8650447078394676


# KNN is slightly better than SVC

# DTC

In [40]:
from sklearn.tree import DecisionTreeClassifier

In [41]:
dtc=DecisionTreeClassifier()

In [42]:
dtc.fit(x_train,y_train)
y_train_pred=dtc.predict(x_train)
y_test_pred=dtc.predict(x_test)

print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
print("confusion_matrix train:\n",confusion_matrix(y_train,y_train_pred))
print("classification_report train:\n",classification_report(y_train,y_train_pred))
print("Precision train: ",precision_score(y_train,y_train_pred),"\n")

print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
print("confusion_matrix test:\n",confusion_matrix(y_test,y_test_pred))
print("classification_report test:\n",classification_report(y_test,y_test_pred))
print("Precision test: ",precision_score(y_test,y_test_pred))

Accuracy train:  0.9728025526095875
confusion_matrix train:
 [[19480   264]
 [  810 18935]]
classification_report train:
               precision    recall  f1-score   support

           0       0.96      0.99      0.97     19744
           1       0.99      0.96      0.97     19745

    accuracy                           0.97     39489
   macro avg       0.97      0.97      0.97     39489
weighted avg       0.97      0.97      0.97     39489

Precision train:  0.9862492838168655 

Accuracy test:  0.8462473412336676
confusion_matrix test:
 [[4208  729]
 [ 789 4147]]
classification_report test:
               precision    recall  f1-score   support

           0       0.84      0.85      0.85      4937
           1       0.85      0.84      0.85      4936

    accuracy                           0.85      9873
   macro avg       0.85      0.85      0.85      9873
weighted avg       0.85      0.85      0.85      9873

Precision test:  0.8504922067268252


# Hyperparamater Tuning

In [45]:
depths=[14,15,16,17,18]
for d in depths:
    
    print("at Depth: ",d,"\n")
    dtc=DecisionTreeClassifier(max_depth=d)
    dtc.fit(x_train,y_train)
    y_train_pred=dtc.predict(x_train)
    y_test_pred=dtc.predict(x_test)
    
    print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
    print("Precision train: ",precision_score(y_train,y_train_pred),"\n")
    print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
    print("Precision test: ",precision_score(y_test,y_test_pred),"\n")

at Depth:  14 

Accuracy train:  0.8962749120008103
Precision train:  0.8884861724839879 

Accuracy test:  0.8617441507140686
Precision test:  0.8497551420176298 

at Depth:  15 

Accuracy train:  0.9031375826179442
Precision train:  0.8973642172523961 

Accuracy test:  0.8627570140788008
Precision test:  0.8515609660318084 

at Depth:  16 

Accuracy train:  0.9088860188913368
Precision train:  0.9023272038670453 

Accuracy test:  0.860933860022283
Precision test:  0.8486983754159326 

at Depth:  17 

Accuracy train:  0.9158499835397199
Precision train:  0.9003412969283277 

Accuracy test:  0.8591107059657652
Precision test:  0.8384571319457704 

at Depth:  18 

Accuracy train:  0.9230418597584137
Precision train:  0.9347803456173225 

Accuracy test:  0.8577939835916135
Precision test:  0.8580697485806975 



In [46]:
features=["auto","sqrt","log2"]

for maxf in features:
    
    print("at Features: ",maxf,"\n")
    dtc=DecisionTreeClassifier(max_depth=15,max_features=maxf)
    dtc.fit(x_train,y_train)
    y_train_pred=dtc.predict(x_train)
    y_test_pred=dtc.predict(x_test)
    
    print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
    print("Precision train: ",precision_score(y_train,y_train_pred),"\n")
    print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
    print("Precision test: ",precision_score(y_test,y_test_pred),"\n")

at Features:  auto 

Accuracy train:  0.8907797108055407
Precision train:  0.8930317848410758 

Accuracy test:  0.854147675478578
Precision test:  0.8542764491284961 

at Features:  sqrt 

Accuracy train:  0.8928562384461496
Precision train:  0.8832131212330797 

Accuracy test:  0.8587055606198724
Precision test:  0.845059442603781 

at Features:  log2 

Accuracy train:  0.8830560409227887
Precision train:  0.8624970045530793 

Accuracy test:  0.8577939835916135
Precision test:  0.8366374380480366 



C:\Users\Shafiq\AppData\Roaming\Python\Python39\site-packages\sklearn\tree\_classes.py:298: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'`.
  warnings.warn(


In [47]:
criterion=["gini","entropy", "log_loss"]

for c in criterion:
    
    print("at crietria: ",c,"\n")
    dtc=DecisionTreeClassifier(max_depth=15,criterion=c)
    dtc.fit(x_train,y_train)
    y_train_pred=dtc.predict(x_train)
    y_test_pred=dtc.predict(x_test)
    
    print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
    print("Precision train: ",precision_score(y_train,y_train_pred),"\n")
    print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
    print("Precision test: ",precision_score(y_test,y_test_pred),"\n")


at crietria:  gini 

Accuracy train:  0.9032135531413812
Precision train:  0.8973795857249813 

Accuracy test:  0.8634660184341132
Precision test:  0.8528717545239969 

at crietria:  entropy 

Accuracy train:  0.8950340601180076
Precision train:  0.8983656792645557 

Accuracy test:  0.8631621594246937
Precision test:  0.8620480710967481 

at crietria:  log_loss 

Accuracy train:  0.8950593836258198
Precision train:  0.8982081780591148 

Accuracy test:  0.8618454370505418
Precision test:  0.8606623586429726 



In [48]:
split=["best","random"]


for s in split:
    
    print("at splitter: ",s,"\n")
    dtc=DecisionTreeClassifier(max_depth=15,criterion="log_loss",splitter=s)
    dtc.fit(x_train,y_train)
    y_train_pred=dtc.predict(x_train)
    y_test_pred=dtc.predict(x_test)
    
    print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
    print("Precision train: ",precision_score(y_train,y_train_pred),"\n")
    print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
    print("Precision test: ",precision_score(y_test,y_test_pred),"\n")


at splitter:  best 

Accuracy train:  0.894907442578946
Precision train:  0.8980550308846802 

Accuracy test:  0.8631621594246937
Precision test:  0.8616098446641114 

at splitter:  random 

Accuracy train:  0.8845754513915267
Precision train:  0.8924086610511085 

Accuracy test:  0.8475640636078193
Precision test:  0.8368348713921068 



In [49]:
min_s=[2,4,6,8]


for ms in min_s:
    
    print("at min_sample: ",ms,"\n")
    dtc=DecisionTreeClassifier(max_depth=15,criterion="log_loss",min_samples_split=ms)
    dtc.fit(x_train,y_train)
    y_train_pred=dtc.predict(x_train)
    y_test_pred=dtc.predict(x_test)
    
    print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
    print("Precision train: ",precision_score(y_train,y_train_pred),"\n")
    print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
    print("Precision test: ",precision_score(y_test,y_test_pred),"\n")


at min_sample:  2 

Accuracy train:  0.8949327660867583
Precision train:  0.898629996932829 

Accuracy test:  0.8622505823964347
Precision test:  0.8615042458552366 

at min_sample:  4 

Accuracy train:  0.8935906201727063
Precision train:  0.8973362646352063 

Accuracy test:  0.8631621594246937
Precision test:  0.8627808136004858 

at min_sample:  6 

Accuracy train:  0.8922484742586543
Precision train:  0.8964881744650354 

Accuracy test:  0.8632634457611669
Precision test:  0.8633968382650993 

at min_sample:  8 

Accuracy train:  0.8907037402821039
Precision train:  0.8954328771336306 

Accuracy test:  0.8632634457611669
Precision test:  0.8645790971939813 



In [50]:
dtc=DecisionTreeClassifier(max_depth=15,criterion="log_loss")
dtc.fit(x_train,y_train)
y_train_pred=dtc.predict(x_train)
y_test_pred=dtc.predict(x_test)

print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
print("confusion_matrix train:\n",confusion_matrix(y_train,y_train_pred))
print("classification_report train:\n",classification_report(y_train,y_train_pred))
print("Precision train: ",precision_score(y_train,y_train_pred),"\n")

print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
print("confusion_matrix test:\n",confusion_matrix(y_test,y_test_pred))
print("classification_report test:\n",classification_report(y_test,y_test_pred))
print("Precision test: ",precision_score(y_test,y_test_pred))

Accuracy train:  0.894907442578946
confusion_matrix train:
 [[17760  1984]
 [ 2166 17579]]
classification_report train:
               precision    recall  f1-score   support

           0       0.89      0.90      0.90     19744
           1       0.90      0.89      0.89     19745

    accuracy                           0.89     39489
   macro avg       0.89      0.89      0.89     39489
weighted avg       0.89      0.89      0.89     39489

Precision train:  0.8985840617492205 

Accuracy test:  0.8624531550693811
confusion_matrix test:
 [[4252  685]
 [ 673 4263]]
classification_report test:
               precision    recall  f1-score   support

           0       0.86      0.86      0.86      4937
           1       0.86      0.86      0.86      4936

    accuracy                           0.86      9873
   macro avg       0.86      0.86      0.86      9873
weighted avg       0.86      0.86      0.86      9873

Precision test:  0.8615602263540825


# DTC performing better than Logreg,SVC and KNN

# RandomForest

In [51]:
from sklearn.ensemble import RandomForestClassifier

In [52]:
rf=RandomForestClassifier()

In [53]:
rf.fit(x_train,y_train)
y_train_pred=rf.predict(x_train)
y_test_pred=rf.predict(x_test)

print("Train accuracy_score: ",accuracy_score(y_train,y_train_pred))
print("Train confusion_matrix: \n",confusion_matrix(y_train,y_train_pred))
print("Train classification_report: \n",classification_report(y_train,y_train_pred))
print("Train precision_score: ",precision_score(y_train,y_train_pred))

print("\n")

print("Test accuracy_score: ",accuracy_score(y_test,y_test_pred))
print("Test confusion_matrix: \n",confusion_matrix(y_test,y_test_pred))
print("Test classification_report: \n",classification_report(y_test,y_test_pred))
print("Test precision_score: ",precision_score(y_test,y_test_pred))

Train accuracy_score:  0.9728025526095875
Train confusion_matrix: 
 [[19288   456]
 [  618 19127]]
Train classification_report: 
               precision    recall  f1-score   support

           0       0.97      0.98      0.97     19744
           1       0.98      0.97      0.97     19745

    accuracy                           0.97     39489
   macro avg       0.97      0.97      0.97     39489
weighted avg       0.97      0.97      0.97     39489

Train precision_score:  0.9767144972680386


Test accuracy_score:  0.8770383875215233
Test confusion_matrix: 
 [[4331  606]
 [ 608 4328]]
Test classification_report: 
               precision    recall  f1-score   support

           0       0.88      0.88      0.88      4937
           1       0.88      0.88      0.88      4936

    accuracy                           0.88      9873
   macro avg       0.88      0.88      0.88      9873
weighted avg       0.88      0.88      0.88      9873

Test precision_score:  0.8771787596270775


# Hyperparameter Tuning

In [55]:
estimators=[200,220,240,260,280,300]
for e in estimators:
    
    print("at estimators: ",e,"\n")
    rf=RandomForestClassifier(n_estimators=e)
    rf.fit(x_train,y_train)
    y_train_pred=rf.predict(x_train)
    y_test_pred=rf.predict(x_test)
    
    print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
    print("Precision train: ",precision_score(y_train,y_train_pred),"\n")
    print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
    print("Precision test: ",precision_score(y_test,y_test_pred),"\n")

at estimators:  200 

Accuracy train:  0.9728025526095875
Precision train:  0.9748715600996999 

Accuracy test:  0.8771396738579965
Precision test:  0.8750755591376184 

at estimators:  220 

Accuracy train:  0.9728025526095875
Precision train:  0.9758397471838524 

Accuracy test:  0.8760255241567912
Precision test:  0.8751010509296685 

at estimators:  240 

Accuracy train:  0.9728025526095875
Precision train:  0.9749198758711909 

Accuracy test:  0.8763293831662109
Precision test:  0.8753283491614468 

at estimators:  260 

Accuracy train:  0.9728025526095875
Precision train:  0.9756457940592042 

Accuracy test:  0.8761268104932645
Precision test:  0.8746720484359233 

at estimators:  280 

Accuracy train:  0.9728025526095875
Precision train:  0.9758882601824947 

Accuracy test:  0.8757216651473716
Precision test:  0.8741174097236232 

at estimators:  300 

Accuracy train:  0.9728025526095875
Precision train:  0.9754519989814108 

Accuracy test:  0.8763293831662109
Precision test:  0

In [60]:
depths=[19]
for d in depths:
    
    print("at Depth: ",d,"\n")
    rf=RandomForestClassifier(n_estimators=240,max_depth=d)
    rf.fit(x_train,y_train)
    y_train_pred=rf.predict(x_train)
    y_test_pred=rf.predict(x_test)
    
    print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
    print("Precision train: ",precision_score(y_train,y_train_pred),"\n")
    print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
    print("Precision test: ",precision_score(y_test,y_test_pred),"\n")

at Depth:  19 

Accuracy train:  0.938565170047355
Precision train:  0.9339948879867689 

Accuracy test:  0.8817988453357642
Precision test:  0.8747265858023464 



In [61]:
features=["auto","sqrt","log2"]

for maxf in features:
    
    print("at Features: ",maxf,"\n")
    rf=RandomForestClassifier(n_estimators=240,max_depth=19,max_features=maxf)
    rf.fit(x_train,y_train)
    y_train_pred=rf.predict(x_train)
    y_test_pred=rf.predict(x_test)
    
    print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
    print("Precision train: ",precision_score(y_train,y_train_pred),"\n")
    print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
    print("Precision test: ",precision_score(y_test,y_test_pred),"\n")

at Features:  auto 



C:\Users\Shafiq\AppData\Roaming\Python\Python39\site-packages\sklearn\ensemble\_forest.py:427: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


Accuracy train:  0.9382866114614197
Precision train:  0.9328731492597039 

Accuracy test:  0.883115567709916
Precision test:  0.8749008723235527 

at Features:  sqrt 

Accuracy train:  0.9388690521411026
Precision train:  0.9342955946474214 

Accuracy test:  0.8837232857287551
Precision test:  0.8769904458598726 

at Features:  log2 

Accuracy train:  0.9387930816176657
Precision train:  0.9339811660989782 

Accuracy test:  0.8832168540463892
Precision test:  0.875968992248062 



In [62]:
rf=RandomForestClassifier(n_estimators=240,max_depth=19,max_features="sqrt")
rf.fit(x_train,y_train)
y_train_pred=rf.predict(x_train)
y_test_pred=rf.predict(x_test)

print("Train accuracy_score: ",accuracy_score(y_train,y_train_pred))
print("Train confusion_matrix: \n",confusion_matrix(y_train,y_train_pred))
print("Train classification_report: \n",classification_report(y_train,y_train_pred))
print("Train precision_score: ",precision_score(y_train,y_train_pred))

print("\n")

print("Test accuracy_score: ",accuracy_score(y_test,y_test_pred))
print("Test confusion_matrix: \n",confusion_matrix(y_test,y_test_pred))
print("Test classification_report: \n",classification_report(y_test,y_test_pred))
print("Test precision_score: ",precision_score(y_test,y_test_pred))

Train accuracy_score:  0.9389196991567272
Train confusion_matrix: 
 [[18449  1295]
 [ 1117 18628]]
Train classification_report: 
               precision    recall  f1-score   support

           0       0.94      0.93      0.94     19744
           1       0.93      0.94      0.94     19745

    accuracy                           0.94     39489
   macro avg       0.94      0.94      0.94     39489
weighted avg       0.94      0.94      0.94     39489

Train precision_score:  0.93499974903378


Test accuracy_score:  0.8837232857287551
Test confusion_matrix: 
 [[4320  617]
 [ 531 4405]]
Test classification_report: 
               precision    recall  f1-score   support

           0       0.89      0.88      0.88      4937
           1       0.88      0.89      0.88      4936

    accuracy                           0.88      9873
   macro avg       0.88      0.88      0.88      9873
weighted avg       0.88      0.88      0.88      9873

Test precision_score:  0.8771405814416567


# RF performing better than DTC

# ETC

In [63]:
from sklearn.ensemble import ExtraTreesClassifier

In [64]:
etc=ExtraTreesClassifier()

In [65]:
etc.fit(x_train,y_train)
y_train_pred=etc.predict(x_train)
y_test_pred=etc.predict(x_test)

print("Train accuracy_score: ",accuracy_score(y_train,y_train_pred))
print("Train confusion_matrix: \n",confusion_matrix(y_train,y_train_pred))
print("Train classification_report: \n",classification_report(y_train,y_train_pred))
print("Train precision_score: ",precision_score(y_train,y_train_pred))

print("\n")

print("Test accuracy_score: ",accuracy_score(y_test,y_test_pred))
print("Test confusion_matrix: \n",confusion_matrix(y_test,y_test_pred))
print("Test classification_report: \n",classification_report(y_test,y_test_pred))
print("Test precision_score: ",precision_score(y_test,y_test_pred))

Train accuracy_score:  0.9728025526095875
Train confusion_matrix: 
 [[19480   264]
 [  810 18935]]
Train classification_report: 
               precision    recall  f1-score   support

           0       0.96      0.99      0.97     19744
           1       0.99      0.96      0.97     19745

    accuracy                           0.97     39489
   macro avg       0.97      0.97      0.97     39489
weighted avg       0.97      0.97      0.97     39489

Train precision_score:  0.9862492838168655


Test accuracy_score:  0.8753165198014787
Test confusion_matrix: 
 [[4229  708]
 [ 523 4413]]
Test classification_report: 
               precision    recall  f1-score   support

           0       0.89      0.86      0.87      4937
           1       0.86      0.89      0.88      4936

    accuracy                           0.88      9873
   macro avg       0.88      0.88      0.88      9873
weighted avg       0.88      0.88      0.88      9873

Test precision_score:  0.8617457527826596


# Hyperparameter Tuning

In [67]:
estimators=[200,220,240,260,280,300]
for e in estimators:
    
    print("at estimators: ",e,"\n")
    etc=ExtraTreesClassifier(n_estimators=e)
    etc.fit(x_train,y_train)
    y_train_pred=etc.predict(x_train)
    y_test_pred=etc.predict(x_test)
    
    print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
    print("Precision train: ",precision_score(y_train,y_train_pred),"\n")
    print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
    print("Precision test: ",precision_score(y_test,y_test_pred),"\n")

at estimators:  200 

Accuracy train:  0.9728025526095875
Precision train:  0.9862492838168655 

Accuracy test:  0.8737972247543806
Precision test:  0.8576967816983326 

at estimators:  220 

Accuracy train:  0.9728025526095875
Precision train:  0.9862492838168655 

Accuracy test:  0.8726830750531753
Precision test:  0.8561471442400774 

at estimators:  240 

Accuracy train:  0.9728025526095875
Precision train:  0.9862492838168655 

Accuracy test:  0.8745062291096931
Precision test:  0.8583058732312464 

at estimators:  260 

Accuracy train:  0.9728025526095875
Precision train:  0.9862492838168655 

Accuracy test:  0.8735946520814342
Precision test:  0.8581973581973582 

at estimators:  280 

Accuracy train:  0.9728025526095875
Precision train:  0.9862492838168655 

Accuracy test:  0.8731895067355414
Precision test:  0.8565621370499419 

at estimators:  300 

Accuracy train:  0.9728025526095875
Precision train:  0.9862492838168655 

Accuracy test:  0.8737972247543806
Precision test:  0

In [72]:
depths=[20,21,22]
for d in depths:
    
    print("at Depth: ",d,"\n")
    etc=ExtraTreesClassifier(n_estimators=240,max_depth=d)
    etc.fit(x_train,y_train)
    y_train_pred=etc.predict(x_train)
    y_test_pred=etc.predict(x_test)
    
    print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
    print("Precision train: ",precision_score(y_train,y_train_pred),"\n")
    print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
    print("Precision test: ",precision_score(y_test,y_test_pred),"\n")

at Depth:  20 

Accuracy train:  0.9188888044771962
Precision train:  0.8897370653095844 

Accuracy test:  0.8747088017826395
Precision test:  0.8367012561441836 

at Depth:  21 

Accuracy train:  0.924991769859961
Precision train:  0.8983622122003323 

Accuracy test:  0.8777473918768358
Precision test:  0.8416712479384277 

at Depth:  22 

Accuracy train:  0.9316771759224087
Precision train:  0.9075304805163759 

Accuracy test:  0.8785576825686215
Precision test:  0.8426554190353933 



In [73]:
features=["auto","sqrt","log2"]

for maxf in features:
    
    print("at Features: ",maxf,"\n")
    etc=ExtraTreesClassifier(n_estimators=240,max_depth=21,max_features=maxf)
    etc.fit(x_train,y_train)
    y_train_pred=etc.predict(x_train)
    y_test_pred=etc.predict(x_test)
    
    print("Accuracy train: ",accuracy_score(y_train,y_train_pred))
    print("Precision train: ",precision_score(y_train,y_train_pred),"\n")
    print("Accuracy test: ",accuracy_score(y_test,y_test_pred))
    print("Precision test: ",precision_score(y_test,y_test_pred),"\n")

at Features:  auto 



C:\Users\Shafiq\AppData\Roaming\Python\Python39\site-packages\sklearn\ensemble\_forest.py:427: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


Accuracy train:  0.9252196814302717
Precision train:  0.899771450338063 

Accuracy test:  0.8787602552415679
Precision test:  0.8451172235554735 

at Features:  sqrt 

Accuracy train:  0.9243333586568412
Precision train:  0.8974431952943409 

Accuracy test:  0.8760255241567912
Precision test:  0.8375773008366679 

at Features:  log2 

Accuracy train:  0.9250424168755856
Precision train:  0.8973909749514655 

Accuracy test:  0.8772409601944697
Precision test:  0.8400292184075968 



In [74]:
etc=ExtraTreesClassifier(n_estimators=240,max_depth=21,max_features="auto")
etc.fit(x_train,y_train)
y_train_pred=etc.predict(x_train)
y_test_pred=etc.predict(x_test)

print("Train accuracy_score: ",accuracy_score(y_train,y_train_pred))
print("Train confusion_matrix: \n",confusion_matrix(y_train,y_train_pred))
print("Train classification_report: \n",classification_report(y_train,y_train_pred))
print("Train precision_score: ",precision_score(y_train,y_train_pred))

print("\n")

print("Test accuracy_score: ",accuracy_score(y_test,y_test_pred))
print("Test confusion_matrix: \n",confusion_matrix(y_test,y_test_pred))
print("Test classification_report: \n",classification_report(y_test,y_test_pred))
print("Test precision_score: ",precision_score(y_test,y_test_pred))

C:\Users\Shafiq\AppData\Roaming\Python\Python39\site-packages\sklearn\ensemble\_forest.py:427: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


Train accuracy_score:  0.9257767986021423
Train confusion_matrix: 
 [[17660  2084]
 [  847 18898]]
Train classification_report: 
               precision    recall  f1-score   support

           0       0.95      0.89      0.92     19744
           1       0.90      0.96      0.93     19745

    accuracy                           0.93     39489
   macro avg       0.93      0.93      0.93     39489
weighted avg       0.93      0.93      0.93     39489

Train precision_score:  0.9006767705652464


Test accuracy_score:  0.877848678213309
Test confusion_matrix: 
 [[4073  864]
 [ 342 4594]]
Test classification_report: 
               precision    recall  f1-score   support

           0       0.92      0.82      0.87      4937
           1       0.84      0.93      0.88      4936

    accuracy                           0.88      9873
   macro avg       0.88      0.88      0.88      9873
weighted avg       0.88      0.88      0.88      9873

Test precision_score:  0.841700256504214


# ETC give slightly less accuracy and precision score than RF. 

# RF here gives the best accuracy out of all 3

In [79]:
import joblib

In [80]:
joblib.dump(rf,"C:/Users/Shafiq/Desktop/arsh LU/adult income/model.pkl")

['C:/Users/Shafiq/Desktop/arsh LU/adult income/model.pkl']